image: registry.tccenter.ru/public/node:15.3.0

variables:
  CI: 'FALSE'

stages:
  - prepare
  - test
  - build
  - publish

install_packages:
  stage: prepare
  allow_failure: false
  timeout: 30 min
  before_script:
    - echo "PACKAGES WILL BE INSTALLED"
  script:
    - yarn install
  after_script:
    - echo "IT RUNS ALWAYS AFTER SECTION script"
  artifacts:
    name: "modules-$CI_COMMIT_REF_SLUG"
    expire_in: 1 week
    paths:
      - node_modules/
    when: "always"
  cache:
    key: yarn-$CI_COMMIT_REF_SLUG
    paths:
      - .yarn/cache/
    policy: pull-push

unit_testing:
  stage: test
  timeout: 30 min
  script:
    - yarn test

e2e_testing:
  allow_failure: true
  stage: test
  script:
    - echo "E2E TESTING RUNNING"

sonar_qube:
  allow_failure: false
  stage: test
  image:
    name: registry.tccenter.ru/public/sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_PROJECT_NAME: ci-test-app
    SONAR_HOST: 'https://sonarqube.tccenter.ru'
  cache:
    key: "sonar-$CI_COMMIT_REF_SLUG"
    paths:
      - .sonar/cache
  script:
    - |
      sonar-scanner \
      -Dsonar.projectKey=$SONAR_PROJECT_NAME \
      -Dsonar.projectBaseDir=. \
      -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
      -Dsonar.sources=src \
      -Dsonar.exclusions=**/*.spec.*,**/*.scss,**/*.test.* \
      -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN
      -Dsonar.qualitygate.wait=true
  only:
    - merge_requests
    - master
    - develop

build:
  stage: build
  allow_failure: false
  timeout: 30 min
  script:
    yarn build
  artifacts:
    name: "build-$CI_COMMIT_REF_SLUG"
    expire_in: 1 week
    paths:
      - build/


publish:
  stage: publish
  image: registry.tccenter.ru/public/docker:18.09-dind
  services:
    - registry.tccenter.ru/public/docker:18.09-dind
  variables:
    harborAddress: "registry.tccenter.ru"
    harborRepository: "it-delivery/ci-test-app"
  when: manual
  before_script:
    - docker login $harborAddress -u ${ITD_USER} -p ${ITD_PASS}
  script:
    - ls
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker build -t $harborAddress/$harborRepository .
    - docker push $harborAddress/$harborRepository
  after_script:
    - docker logout $harborAddress
